apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kong-service-backend-hpa
  namespace: kong-service
  labels:
    app: kong-service-backend
    tier: autoscaler
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "HPA para autoescalonamento do kong com base na utilização de CPU"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kong-service-backend
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
